<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HASEEFRAWTHAR" failures="2" tests="4" name="Cucumber with TestNG Test" time="5.795" errors="0" timestamp="2022-10-03T17:55:39 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="2.955">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at com.NopCommerce.api.stepdefenition.APISteps.a_success_response_is_received(APISteps.java:238)
at ✽.A success response is received(file:///D:/NopCommerce/src/test/java/com/NopCommerce/api/feature/DeleteUser.feature:7)
... Removed 5 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.92"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.626"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.865">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at com.NopCommerce.api.stepdefenition.APISteps.a_success_response_is_received(APISteps.java:238)
at ✽.A success response is received(file:///D:/NopCommerce/src/test/java/com/NopCommerce/api/feature/PutUser.feature:7)
... Removed 5 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Cucumber with TestNG Test -->
